#pragma once

#define UNIFORM_BUFFER_VIEW_INFO_BINDING_LOCATION 1
#define UNIFORM_BUFFER_MATERIAL_INFO_BINDING_LOCATION 10


#define DEFAULT_FOV (glm::pi<float>() * 0.6f)
#define DEFAULT_Z_NEAR 0.1f
#define DEFAULT_Z_FAR 100.f